### This EDA Answers the Following Questions

1. **Do all EEG subsets have the same label?**  
2. **How is the EEG data arranged?**

In [2]:
import pandas as pd
import numpy as np

In [3]:
import os
os.getcwd()

'f:\\Python_Project\\HMS_EEG\\notebooks'

In [4]:
# Q1

df = pd.read_csv("../Data/train.csv")
# Group by eeg_id and check if all Expert_consensus values are the same
inconsistent_ids = df.groupby('eeg_id')['expert_consensus'].nunique()
inconsistent_ids = inconsistent_ids[inconsistent_ids > 1]

# Print result
if inconsistent_ids.empty:
    print("All Expert_consensus values are consistent within each eeg_id.")
else:
    print("Inconsistent Expert_consensus values found for the following eeg_id(s):")
    print(inconsistent_ids)

Inconsistent Expert_consensus values found for the following eeg_id(s):
eeg_id
21379701      3
21746311      2
32067830      2
36718960      2
37347312      2
             ..
4268492759    2
4279656286    2
4282888597    2
4283246598    2
4284659653    4
Name: expert_consensus, Length: 783, dtype: int64

In [5]:
df.head(10)

,eeg_id,eeg_sub_id,eeg_label_offset_seconds,spectrogram_id,spectrogram_sub_id,spectrogram_label_offset_seconds,label_id,patient_id,expert_consensus,seizure_vote,lpd_vote,gpd_vote,lrda_vote,grda_vote,other_vote
0,1628180742,0,0.0,353733,0,0.0,127492639,42516,Seizure,3,0,0,0,0,0
1,1628180742,1,6.0,353733,1,6.0,3887563113,42516,Seizure,3,0,0,0,0,0
2,1628180742,2,8.0,353733,2,8.0,1142670488,42516,Seizure,3,0,0,0,0,0
3,1628180742,3,18.0,353733,3,18.0,2718991173,42516,Seizure,3,0,0,0,0,0
4,1628180742,4,24.0,353733,4,24.0,3080632009,42516,Seizure,3,0,0,0,0,0
5,1628180742,5,26.0,353733,5,26.0,2413091605,42516,Seizure,3,0,0,0,0,0
6,1628180742,6,30.0,353733,6,30.0,364593930,42516,Seizure,3,0,0,0,0,0
7,1628180742,7,36.0,353733,7,36.0,3811483573,42516,Seizure,3,0,0,0,0,0
8,1628180742,8,40.0,353733,8,40.0,3388718494,42516,Seizure,3,0,0,0,0,0
9,2277392603,0,0.0,924234,0,0.0,1978807404,30539,GPD,0,0,5,0,1,5

In [13]:
spec_data_example = pd.read_parquet("../Data/train_spectrograms/924234.parquet")
spec_data_example.head()

,time,LL_0.59,LL_0.78,LL_0.98,LL_1.17,LL_1.37,LL_1.56,LL_1.76,LL_1.95,LL_2.15,...,RP_18.16,RP_18.36,RP_18.55,RP_18.75,RP_18.95,RP_19.14,RP_19.34,RP_19.53,RP_19.73,RP_19.92
0,1,8.95,9.15,10.98,8.71,8.29,7.15,5.90,5.14,5.26,...,0.04,0.03,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.03
1,3,6.84,7.35,7.54,5.67,3.42,3.82,4.11,4.96,5.50,...,0.03,0.02,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03
2,5,4.54,4.88,4.41,3.70,1.75,2.44,3.15,5.74,6.27,...,0.01,0.01,0.01,0.01,0.01,0.02,0.02,0.02,0.02,0.01
3,7,4.98,6.42,6.38,6.25,5.95,4.92,3.84,3.53,3.71,...,0.01,0.01,0.02,0.01,0.02,0.02,0.02,0.01,0.01,0.01
4,9,8.44,7.93,9.19,6.32,4.17,4.53,3.05,3.70,3.56,...,0.01,0.01,0.02,0.02,0.02,0.02,0.01,0.01,0.01,0.01

In [7]:
eeg_file_name = df.loc[df["spectrogram_id"]==924234, "eeg_id"].iloc[0]
eeg_data_example = pd.read_parquet(f"../Data/train_eegs/{eeg_file_name}.parquet")
eeg_data_example.head()

,Fp1,F3,C3,P3,F7,T3,T5,O1,Fz,Cz,Pz,Fp2,F4,C4,P4,F8,T4,T6,O2,EKG
0,6.93,2.92,32.240002,5.59,23.190001,24.129999,35.189999,23.629999,-15.31,-6.59,-5.11,-25.850000,-4.97,17.830000,-36.639999,2.80,-6.70,-13.870000,-17.770000,12.030000
1,11.92,7.85,35.720001,16.02,25.700001,24.080000,34.650002,26.190001,-8.81,-4.97,-4.54,-20.860001,-0.98,17.820000,-25.639999,3.76,-8.80,-14.800000,-16.100000,28.650000
2,15.48,10.61,34.720001,26.41,26.959999,20.129999,32.990002,25.900000,-1.85,-2.51,-3.65,-14.860000,3.21,18.760000,-15.500000,3.39,-11.83,-15.370000,-16.040001,31.340000
3,7.77,4.42,31.670000,5.94,22.350000,21.040001,31.690001,19.850000,-12.00,-7.85,-9.41,-23.350000,-2.60,16.389999,-36.040001,3.11,-8.40,-16.780001,-20.840000,12.780000
4,7.88,4.21,31.750000,4.04,22.120001,20.629999,31.690001,19.469999,-13.07,-9.36,-11.79,-24.650000,-3.83,14.040000,-38.110001,2.86,-8.32,-17.790001,-22.219999,21.030001

In [19]:
spec_data_example.shape, eeg_data_example.shape

((301, 401), (13200, 20))

In [ ]:
import pywt

NAMES = ['LL','LP','RP','RR']

FEATS = [['Fp1','F7','T3','T5','O1'],
         ['Fp1','F3','C3','P3','O1'],
         ['Fp2','F8','T4','T6','O2'],
         ['Fp2','F4','C4','P4','O2']]

print("The wavelet functions we can use:")
print(pywt.wavelist())

USE_WAVELET =  "db8" #or "db8" or anything below

# The wavelet functions we can use:
# ['bior1.1', 'bior1.3', 'bior1.5', 'bior2.2', 'bior2.4', 'bior2.6', 'bior2.8', 'bior3.1', 'bior3.3', 'bior3.5', 'bior3.7', 'bior3.9', 'bior4.4', 'bior5.5', 'bior6.8', 'cgau1', 'cgau2', 'cgau3', 'cgau4', 'cgau5', 'cgau6', 'cgau7', 'cgau8', 'cmor', 'coif1', 'coif2', 'coif3', 'coif4', 'coif5', 'coif6', 'coif7', 'coif8', 'coif9', 'coif10', 'coif11', 'coif12', 'coif13', 'coif14', 'coif15', 'coif16', 'coif17', 'db1', 'db2', 'db3', 'db4', 'db5', 'db6', 'db7', 'db8', 'db9', 'db10', 'db11', 'db12', 'db13', 'db14', 'db15', 'db16', 'db17', 'db18', 'db19', 'db20', 'db21', 'db22', 'db23', 'db24', 'db25', 'db26', 'db27', 'db28', 'db29', 'db30', 'db31', 'db32', 'db33', 'db34', 'db35', 'db36', 'db37', 'db38', 'dmey', 'fbsp', 'gaus1', 'gaus2', 'gaus3', 'gaus4', 'gaus5', 'gaus6', 'gaus7', 'gaus8', 'haar', 'mexh', 'morl', 'rbio1.1', 'rbio1.3', 'rbio1.5', 'rbio2.2', 'rbio2.4', 'rbio2.6', 'rbio2.8', 'rbio3.1', 'rbio3.3', 'rbio3.5', 'rbio3.7', 'rbio3.9', 'rbio4.4', 'rbio5.5', 'rbio6.8', 'shan', 'sym2', 'sym3', 'sym4', 'sym5', 'sym6', 'sym7', 'sym8', 'sym9', 'sym10', 'sym11', 'sym12', 'sym13', 'sym14', 'sym15', 'sym16', 'sym17', 'sym18', 'sym19', 'sym20']

# DENOISE FUNCTION
def maddest(d, axis=None):
    return np.mean(np.absolute(d - np.mean(d, axis)), axis)

def denoise(x, wavelet='haar', level=1):    
    coeff = pywt.wavedec(x, wavelet, mode="per")
    sigma = (1/0.6745) * maddest(coeff[-level])

    uthresh = sigma * np.sqrt(2*np.log(len(x)))
    coeff[1:] = (pywt.threshold(i, value=uthresh, mode='hard') for i in coeff[1:])

    ret=pywt.waverec(coeff, wavelet, mode='per')
    
    return ret

import librosa

def spectrogram_from_eeg(parquet_path, display=False):
    
    # LOAD MIDDLE 50 SECONDS OF EEG SERIES
    eeg = pd.read_parquet(parquet_path)
    middle = (len(eeg)-10_000)//2
    eeg = eeg.iloc[middle:middle+10_000]
    
    # VARIABLE TO HOLD SPECTROGRAM
    img = np.zeros((128,256,4),dtype='float32')
    
    if display: plt.figure(figsize=(10,7))
    signals = []
    for k in range(4):
        COLS = FEATS[k]
        
        for kk in range(4):
        
            # COMPUTE PAIR DIFFERENCES
            x = eeg[COLS[kk]].values - eeg[COLS[kk+1]].values

            # FILL NANS
            m = np.nanmean(x)
            if np.isnan(x).mean()<1: x = np.nan_to_num(x,nan=m)
            else: x[:] = 0

            # DENOISE
            if USE_WAVELET:
                x = denoise(x, wavelet=USE_WAVELET)
            signals.append(x)

            # RAW SPECTROGRAM
            mel_spec = librosa.feature.melspectrogram(y=x, sr=200, hop_length=len(x)//256, 
                  n_fft=1024, n_mels=128, fmin=0, fmax=20, win_length=128)

            # LOG TRANSFORM
            width = (mel_spec.shape[1]//32)*32
            mel_spec_db = librosa.power_to_db(mel_spec, ref=np.max).astype(np.float32)[:,:width]

            # STANDARDIZE TO -1 TO 1
            mel_spec_db = (mel_spec_db+40)/40 
            img[:,:,k] += mel_spec_db
                
        # AVERAGE THE 4 MONTAGE DIFFERENCES
        img[:,:,k] /= 4.0
        
        if display:
            plt.subplot(2,2,k+1)
            plt.imshow(img[:,:,k],aspect='auto',origin='lower')
            plt.title(f'EEG {eeg_id} - Spectrogram {NAMES[k]}')
            
    if display: 
        plt.show()
        plt.figure(figsize=(10,5))
        offset = 0
        for k in range(4):
            if k>0: offset -= signals[3-k].min()
            plt.plot(range(10_000),signals[k]+offset,label=NAMES[3-k])
            offset += signals[3-k].max()
        plt.legend()
        plt.title(f'EEG {eeg_id} Signals')
        plt.show()
        print(); print('#'*25); print()
        
    return img

The wavelet functions we can use:
['bior1.1', 'bior1.3', 'bior1.5', 'bior2.2', 'bior2.4', 'bior2.6', 'bior2.8', 'bior3.1', 'bior3.3', 'bior3.5', 'bior3.7', 'bior3.9', 'bior4.4', 'bior5.5', 'bior6.8', 'cgau1', 'cgau2', 'cgau3', 'cgau4', 'cgau5', 'cgau6', 'cgau7', 'cgau8', 'cmor', 'coif1', 'coif2', 'coif3', 'coif4', 'coif5', 'coif6', 'coif7', 'coif8', 'coif9', 'coif10', 'coif11', 'coif12', 'coif13', 'coif14', 'coif15', 'coif16', 'coif17', 'db1', 'db2', 'db3', 'db4', 'db5', 'db6', 'db7', 'db8', 'db9', 'db10', 'db11', 'db12', 'db13', 'db14', 'db15', 'db16', 'db17', 'db18', 'db19', 'db20', 'db21', 'db22', 'db23', 'db24', 'db25', 'db26', 'db27', 'db28', 'db29', 'db30', 'db31', 'db32', 'db33', 'db34', 'db35', 'db36', 'db37', 'db38', 'dmey', 'fbsp', 'gaus1', 'gaus2', 'gaus3', 'gaus4', 'gaus5', 'gaus6', 'gaus7', 'gaus8', 'haar', 'mexh', 'morl', 'rbio1.1', 'rbio1.3', 'rbio1.5', 'rbio2.2', 'rbio2.4', 'rbio2.6', 'rbio2.8', 'rbio3.1', 'rbio3.3', 'rbio3.5', 'rbio3.7', 'rbio3.9', 'rbio4.4', 'rbio5.5', 'rbio6.8', 'shan', 'sym2', 'sym3', 'sym4', 'sym5', 'sym6', 'sym7', 'sym8', 'sym9', 'sym10', 'sym11', 'sym12', 'sym13', 'sym14', 'sym15', 'sym16', 'sym17', 'sym18', 'sym19', 'sym20']